apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: authorization-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: authorization-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: policy-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: policy-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: claims-billing-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: claims-billing-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: notification-worker
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: notification-worker
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: search-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: search-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: operations-portal
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: operations-portal
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: apisix
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: apisix
