apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-runtime
data:
  CONSOLE_LOG_FORMAT: ecs
  KEYCLOAK_ISSUER_URI: https://identity.health-insurance.example/realms/health-insurance
  KEYCLOAK_JWK_SET_URI: http://keycloak.platform-dependencies.svc.cluster.local:8080/realms/health-insurance/protocol/openid-connect/certs
  KAFKA_BOOTSTRAP_SERVERS: kafka.platform-dependencies.svc.cluster.local:9092
  RABBITMQ_HOST: rabbitmq.platform-dependencies.svc.cluster.local
  ELASTICSEARCH_URIS: http://elasticsearch.platform-dependencies.svc.cluster.local:9200
  ELASTIC_APM_SERVER_URL: http://apm-server.platform-observability.svc.cluster.local:8200
  ELASTIC_APM_ENVIRONMENT: production
  REDIS_HOST: redis.platform-dependencies.svc.cluster.local
  REDIS_PORT: "6379"
  POLICY_SERVICE_BASE_URL: http://policy-service:8082
  AUTHORIZATION_SERVICE_BASE_URL: http://authorization-service:8081
  CORS_ALLOWED_ORIGINS: https://operations.health-insurance.example
  SEARCH_INDEX_ALIAS: healthcare-operations
  SEARCH_INDEX_NAME: healthcare-operations-v1
