apiVersion: v1
kind: ServiceAccount
metadata:
  name: authorization-service
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: policy-service
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: claims-billing-service
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-worker
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: search-service
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operations-portal
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apisix
automountServiceAccountToken: false
