sonar.projectKey=health-insurance-platform
sonar.projectName=Health Insurance Platform
sonar.sourceEncoding=UTF-8

sonar.sources=services/authorization-service/src/main/java,services/policy-service/src/main/java,services/claims-billing-service/src/main/java,services/notification-worker/src/main/java,services/search-service/src/main/java,apps/operations-portal/src
sonar.tests=services/authorization-service/src/test/java,services/policy-service/src/test/java,services/claims-billing-service/src/test/java,services/notification-worker/src/test/java,services/search-service/src/test/java,apps/operations-portal/src
sonar.test.inclusions=**/*Test.java,**/*Tests.java,**/*.test.ts,**/*.test.tsx

sonar.java.binaries=services/authorization-service/target/classes,services/policy-service/target/classes,services/claims-billing-service/target/classes,services/notification-worker/target/classes,services/search-service/target/classes
sonar.java.test.binaries=services/authorization-service/target/test-classes,services/policy-service/target/test-classes,services/claims-billing-service/target/test-classes,services/notification-worker/target/test-classes,services/search-service/target/test-classes

sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/generated/**,**/*.d.ts,**/*.test.ts,**/*.test.tsx
sonar.coverage.exclusions=**/configuration/**,**/dto/**,**/request/**,**/response/**
