server:
  port: 8081
  shutdown: graceful

spring:
  application:
    name: authorization-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/authorization}
    username: ${DB_USERNAME:authorization}
    password: ${DB_PASSWORD:authorization}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/health-insurance}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/health-insurance/protocol/openid-connect/certs}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized
