apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../kubernetes/base

images:
  - name: health-insurance/authorization-service
    newName: host.minikube.internal:8088/health-insurance/authorization-service
    newTag: 7fc3ea6b1086d3f5be2d7adeb9f43bda6bd6ad8d
  - name: health-insurance/policy-service
    newName: host.minikube.internal:8088/health-insurance/policy-service
    newTag: 7fc3ea6b1086d3f5be2d7adeb9f43bda6bd6ad8d
  - name: health-insurance/claims-billing-service
    newName: host.minikube.internal:8088/health-insurance/claims-billing-service
    newTag: 7fc3ea6b1086d3f5be2d7adeb9f43bda6bd6ad8d
  - name: health-insurance/notification-worker
    newName: host.minikube.internal:8088/health-insurance/notification-worker
    newTag: 7fc3ea6b1086d3f5be2d7adeb9f43bda6bd6ad8d
  - name: health-insurance/search-service
    newName: host.minikube.internal:8088/health-insurance/search-service
    newTag: 7fc3ea6b1086d3f5be2d7adeb9f43bda6bd6ad8d
  - name: health-insurance/operations-portal
    newName: host.minikube.internal:8088/health-insurance/operations-portal
    newTag: 7fc3ea6b1086d3f5be2d7adeb9f43bda6bd6ad8d
