apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: health-insurance
  namespace: argocd
spec:
  description: Restricted Health Insurance Platform GitOps boundary
  sourceRepos:
    - https://github.com/aydindemir1/health-insurance-platform.git
  destinations:
    - namespace: health-insurance
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: LimitRange
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: apps
      kind: Deployment
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: policy
      kind: PodDisruptionBudget
  orphanedResources:
    warn: true
